services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: 'django-insecure-4c_bf)y9yep1*!7xta3jwyvq3ty)-(#rhr-ay0i6dmcbt)8sof'
      - key: DJANGO_ALLOWED_HOSTS
        value: voyageAI-backend.onrender.com
